- name: Deploy Webpage
  hosts: all
  become: false
  vars_files:
    - files/vars.yaml
  tasks:
    - name: Install Webpage Dependencies
      local_action: 
        module: ansible.builtin.command
        cmd: "{{ install_cmd }}"
        chdir: "{{ src_dir }}"
    - name: Build Webpage
      local_action: 
        module: ansible.builtin.command
        cmd: "{{ build_cmd }}"
        chdir: "{{ src_dir }}"
    - name: Clean target directory
      ansible.builtin.file:
        path: "{{ remote_target_dir }}"
        state: "absent"
    - name: Create remote target directory
      ansible.builtin.file:
        path: "{{ remote_target_dir }}"
        state: "directory"
    - name: Copy Web App
      ansible.builtin.synchronize:
        src: "{{ publish_dir }}"
        dest: "{{ remote_target_dir }}"
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted
