- name: Update the system
  hosts: all
  become: true
  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600
    - name: Upgrade all packages
      ansible.builtin.apt:
        upgrade: yes
        autoremove: yes
        autoclean: yes
        force_apt_get: yes

- name: Install Dependencies
  hosts: all
  become: true
  tasks:
    - name: Install Nginx
      ansible.builtin.apt:
        state: present
        pkg:
          - nginx
    - name: Install Certbot
      community.general.snap:
        state: present
        name: certbot
        classic: true
    - name: Link Certbot
      ansible.builtin.file:
        src: /snap/bin/certbot
        dest: /usr/bin/certbot
        state: link

- name: Configure Nginx
  hosts: all
  vars_files:
    - files/vars.yaml
  tasks:
    - name: Apply Nginx template
      template:
        src: files/nginx.conf.j2
        dest: /etc/nginx/sites-available/kellnr
      notify: Restart Nginx
    - name: Enable new site
      file:
        src: /etc/nginx/sites-available/kellnr
        dest: /etc/nginx/sites-enabled/kellnr
        state: link
      notify: Restart Nginx
    - name: Configure TLS
      ansible.builtin.command:
        cmd: "certbot --nginx --non-interactive --agree-tos -m {{ email }} -d {{ server_name }} -d {{ www_server_name }}" 
      notify: Restart Nginx
  handlers:
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted
